### ISSUE TITLE
Decentralized Custody

### ISSUE THREAD

**Issue by JohnMcW** [apache/incubator-milagro-dta#1]
As a user, I would like to configure my Milagro Server as both a principal and beneficiary, and to use another Milagro Server as the fiduciary.
![Milagro%20Node](https://user-images.githubusercontent.com/95958/61301330-95897200-a7db-11e9-9b22-03f0cd14106d.png)

**Comment by JohnMcW** [comment]
Was issue https://issues.apache.org/jira/browse/MILAGRO-35 in Apache Jira - that issue will be closed presently

**Comment by howardkitto** [comment]
The beneficiary is nominated in the order. To make the Principal the beneficiary it just needs to use its own ID as the beneficiary
