### ISSUE TITLE
Sample Docker Build is Not Working

### ISSUE THREAD

**Issue by XD-DENG** [apache/incubator-milagro-dta#55]
In README, a sample code for docker build is provided. However, seems it is not working.

I tried to run docker build in different environment, and got "exit status 2" at step `$GOPATH/bin/milagro init`.

In CI process, it is `Dockerfile-alpine` being used, rather than `Dockerfile` which is used in the sample Docker build command.

**Comment by smihaylov** [comment]
@XD-DENG thanks for reporting that. The problem is related to changes of the apache-milagro-crypto-c library which should be applied here. This https://github.com/apache/incubator-milagro-dta/pull/56 should fix the build

**Comment by XD-DENG** [comment]
Thanks @smihaylov . I will test again after #56 is merged and close this issue if everything ok. 

Thanks.

**Comment by XD-DENG** [comment]
Build succeeded with the latest code in master branch. Closing this issue now.
Thanks for the prompt response @smihaylov
